FROM couchbase/server:7.6.5
#COPY create_fixtures.sql /docker-entrypoint-initdb.d/create_fixtures.sql

COPY ./init-scripts/couchbase /usr/local/bin/maintenance
RUN chmod +x /usr/local/bin/maintenance/*
RUN mv /usr/local/bin/maintenance/* /usr/local/bin \
    && rmdir /usr/local/bin/maintenance
RUN mkdir -p /opt/couchbase/backup

ENTRYPOINT ["sh", "-c", "init.sh & /entrypoint.sh couchbase-server"]
