version: '3.8'
services:
  couchbase:
    container_name: couchbase
    image: couchbase/server:7.2.0
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"
    volumes:
      - couchbase_data:/opt/couchbase/var
      - ./init-scripts:/docker-entrypoint-initdb.d
      - couchbase_init:/opt/couchbase/init_done
      - ./backups:/opt/couchbase/backup
    env_file:
      - .env
    environment:
      - COUCHBASE_BUCKET=vector_store
      - COUCHBASE_BUCKET_RAMSIZE=512
    command: sh -c "/docker-entrypoint-initdb.d/init.sh & /entrypoint.sh couchbase-server"

volumes:
  couchbase_data:
  couchbase_init: 