"""history

Revision ID: 6940befda9e3
Revises: dc8d85194fb9
Create Date: 2025-02-24 08:43:11.238646

"""
import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6940befda9e3'
down_revision: Union[str, None] = 'dc8d85194fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('search_text', sa.TEXT(), nullable=False),
    sa.Column('answer_text', sa.TEXT(), nullable=False),
    sa.Column('is_error', sa.BOOLEAN(), nullable=False, default=False),
    sa.Column('search_type', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, default=datetime.datetime.now()),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, default=datetime.datetime.now(), onupdate=datetime.datetime.now()),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###
