"""search_from_inet

Revision ID: dc8d85194fb9
Revises: a7786ab5f7bc
Create Date: 2025-02-15 22:25:27.331911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision: str = 'dc8d85194fb9'
down_revision: Union[str, None] = 'a7786ab5f7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('search_from_inet', sa.BOOLEAN(), nullable=False, server_default=expression.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'search_from_inet')
    # ### end Alembic commands ###
